apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-build-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: distribution
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
    control-plane: controller-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "operator.fullname" . }}-build-cache
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 5000