apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.solver.se.quencer.io
  labels:
    app: {{ include "operator.fullname" . }}-solver
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace}}/{{ include "operator.fullname" . }}-solver
spec:
  group: solver.se.quencer.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: {{ include "operator.fullname" . }}-solver
    namespace: {{ .Release.Namespace }}
  version: v1alpha1
