apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "operator.fullname" . }}-solver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: solver
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
  {{- include "operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "operator.fullname" . }}-solver.{{ .Release.Namespace }}.svc
  - {{ include "operator.fullname" . }}-solver.{{ .Release.Namespace }}.svc.cluster.local
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: {{ include "operator.fullname" . }}-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ .Values.solver.privateKeySecretRef.name }}