apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}-solver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: solver
    app.kubernetes.io/instance: {{ include "operator.fullname" . }}-solver
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: sequencer
  {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.solver.replicaCount }}
  selector:
    matchLabels:
      {{ include "operator.labels" . | nindent 6 }}
      app.kubernetes.io/name: solver
      app.kubernetes.io/instance: {{ include "operator.fullname" . }}-solver
  template:
    metadata:
      labels:
        {{ include "operator.labels" . | nindent 8 }}
        app.kubernetes.io/name: solver
        app.kubernetes.io/instance: {{ include "operator.fullname" . }}-solver
    spec:
      serviceAccountName: {{ include "operator.fullname" . }}-solver
      containers:
        - name: solver
          image: "{{ .Values.solver.image.repository }}:{{ .Values.solver.image.tag }}"
          imagePullPolicy: {{ .Values.solver.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: {{ .Values.solver.groupName | quote }}
            - name: SOLVER_NAME
              value: {{ .Values.solver.name | quote }}
            - name: SEQUENCER_NAMESPACE
              value: {{ .Release.Namespace }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {{ toYaml .Values.solver.resources | indent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.solver.privateKeySecretRef.name }}
    {{- with .Values.solver.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.solver.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.solver.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}