apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-solver
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: solver
    app.kubernetes.io/instance: {{ include "operator.fullname" . }}-solver
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: sequencer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: solver
    app.kubernetes.io/instance: {{ include "operator.fullname" . }}-solver
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/part-of: sequencer
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https