apiVersion: github.com/pier-oliviert/sequencer/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/instance: workspace-sample
    app.kubernetes.io/managed-by: sequencer
    app.kubernetes.io/created-by: sequencer
  generateName: ws-
  namespace: sequencer-system
spec:
  networking:
    dns:
      zone: pier-olivier.dev
    tunnel:
      cloudflare:
        connector: cloudflared
        accountId: $(YOUR_ACCOUNT_ID)
        route:
          component: click-mania
          network: http
        secretKeyRef:
            namespace: default
            name: cloudflare-api-token
            key: apiKey
  components:
    - name: redis
      networks:
        - name: tcp
          port: 6379
          targetPort: 6379
      template:
        containers:
          - name: redis
            image: redis:latest
            ports: 
              - containerPort: 6379
    - name: mysql
      networks:
        - name: tcp
          port: 3306
          targetPort: 3306
      template:
        containers:
          - name: mysql
            image: mysql:latest
            env:
              - name: MYSQL_RANDOM_ROOT_PASSWORD
                value: "true"
              - name: MYSQL_PASSWORD
                value: whatever
              - name: MYSQL_USER
                value: potest
              - name: MYSQL_DATABASE
                value: mydb
            ports: 
              - containerPort: 3306
    - name: click-mania
      dependsOn:
        - componentName: mysql
          conditionType: Pod
          conditionStatus: Healthy
        - componentName: redis
          conditionType: Pod
          conditionStatus: Healthy
      template:
        containers:
          - name: click
            image: ${build::clickaroo}
            ports:
              - containerPort: 3000
            env:
              - name: DB_HOST
                value: ${components::mysql.networks.tcp}
              - name: REDIS_HOST
                value: ${components::redis.networks.tcp}
              - name: DB_NAME
                value: mydb
              - name: DB_USER
                value: potest
              - name: DB_PASSWORD
                value: whatever
            command:
              - /srv/aurora-test
              - start
      networks:
        - name: http
          port: 3000
          targetPort: 3000
      build:
        name: clickaroo
        dockerfile: Dockerfile
        containerRegistries:
          - url: pothibo/sequencer-buildresult
            tags:
              - foo
              - bar
            credentials:
              authScheme: keyPair
              secretRef:
                name: dockerhub-credentials
        importContent:
          - credentials:
              authScheme: token
              secretRef:
                name: github-credentials
            contentFrom:
              git:
                ref: main
                url: git@github.com:pier-oliviert/cookie-clicker.git
