apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}:controller
  labels:
    app.kubernetes.io/component: controller
  {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}:controller
subjects:
- kind: ServiceAccount
  name: {{ include "operator.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
