apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}:controller
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - builds
  - dnsrecords
  - components
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces/finalizers
  - dnsrecords/finalizers
  - builds/finalizers
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces/status
  - dnsrecords/status
  - builds/status
  - components/status
  verbs:
  - get
  - patch
  - update
