apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operator.fullname" . }}:leader-election
  labels:
    app.kubernetes.io/component: controller
  {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.fullname" . }}:leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "operator.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
