apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
  {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sequencerController.serviceAccount.annotations | nindent 4 }}