policy: sync
interval: 10s
provider: 
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiKey

sources:
  - service
  - ingress
  - crd