{{- if .Values.github.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operator.fullname" . }}:github-leader-election
  labels:
    app.kubernetes.io/component: github
  {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.fullname" . }}:github-leader
subjects:
- kind: ServiceAccount
  name: {{ include "operator.fullname" . }}-github
  namespace: {{ .Release.Namespace }}

{{- end }}
