{{- if .Values.github.enabled }}

# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: github
    {{- include "operator.labels" . | nindent 4 }}
  name: {{ include "operator.fullname" . }}:github-leader
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

{{- end }}
