apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-docker-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
data:
  config.yml: |-
    version: 0.1
    delete:
      enabled: true
    log:
      level: info
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      tls:
        certificate: /srv/certs/tls.crt
        key: /srv/certs/tls.key
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    proxy:
      remoteurl: https://registry-1.docker.io
      ttl: 168h