apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "operator.fullname" . }}-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "operator.fullname" . }}-serving-cert
  labels:
  {{- include "operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-se-quencer-io-v1alpha1-build
  failurePolicy: Fail
  name: vbuild.se.quencer.io
  rules:
  - apiGroups:
    - se.quencer.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - builds
  sideEffects: None