apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: sequencer
spec:
  type: ClusterIP
  selector:
    control-plane: sequencer-controller
    {{- include "operator.labels" . | nindent 4 }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
