apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: sequencer
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: sequencer-controller
    {{- include "operator.labels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 }}
