apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "operator.fullname" . }}-acme-issuer
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.certManager.email | quote }}
    server: {{ .Values.certManager.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef.name | quote }}
    solvers:
      - dns01:
          webhook:
            groupName: solver.se.quencer.io
            solverName: {{ include "operator.fullname" . }}-solver
