apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}