apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dns-sequencer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: sequencer
  name: dns-sequencer-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-sequencer-leader-election
subjects:
- kind: ServiceAccount
  name: dns-sequencer-manager
  namespace: sequencer-system
