apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: dns-sequencer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: sequencer
  name: dns-sequencer-manager
  namespace: sequencer-system
