certManager:
  serviceAccount:
    name: cert-manager
    namespace: cert-manager
  server: https://acme-v02.api.letsencrypt.org/directory
  email: your@email.com
  privateKeySecretRef:
    name: acme-cert-tls

distribution:
  image: registry:latest
  buildCache:
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 400m
        memory: 2Gi
  dockerCache:
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 400m
        memory: 2Gi

sequencer:
  image: pothibo/sequencer-operator:0.0.1
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}


builder:
  image: pothibo/sequencer-builder:0.0.1
  pullPolicy: IfNotPresent
  buildkitVersion: v0.12.4

solver:
  image: pothibo/sequencer-solver:0.0.1
  privateKeySecretRef:
    name: acme-cert-tls
  replicas: 1

dns:
  image: pothibo/sequencer-dns:0.0.1
  providerName: undefined
  serviceAccount:
    annotations: {}
  env:
