apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-buildkitd
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  buildkitd.toml: |-
    debug = true
    [registry."docker.io"]
      mirrors = ["{{ include "operator.fullname" . }}-docker-cache.{{ .Release.Namespace}}.svc.cluster.local"]
    [registry."{{ include "operator.fullname" . }}-docker-cache.{{ .Release.Namespace}}.svc.cluster.local"]
    ca=["/srv/certs/ca.crt"]
    [[registry."{{ include "operator.fullname" . }}-docker-cache.{{ .Release.Namespace}}.svc.cluster.local".keypair]]
      key="/srv/certs/tls.key"
      cert="/srv/certs/tls.crt"
    [registry."{{ include "operator.fullname" . }}-build-cache.{{ .Release.Namespace}}.svc.cluster.local"]
    ca=["/srv/certs/ca.crt"]
    [[registry."{{ include "operator.fullname" . }}-build-cache.{{ .Release.Namespace}}.svc.cluster.local".keypair]]
      key="/srv/certs/tls.key"
      cert="/srv/certs/tls.crt"