apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  BUILD_CACHE_SVC: {{ include "operator.fullname" . }}-build-cache
  CONTROLLER_SERVICE_ACCOUNT: {{ include "operator.fullname" . }}-controller-manager
  BUILDKITD_CONFIG_NAME: {{ include "operator.fullname" . }}-buildkitd
  BUILDER_IMAGE: {{ .Values.controllerManager.builderImage | quote }}
  BUILDKIT_VERSION: {{ .Values.controllerManager.buildkitVersion | quote }}