apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
  {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}