{{- $providerName := tpl (include "operator.externalDNS.providerName" .) $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}-external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: {{ include "operator.fullname" . }}-external-dns
    {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.externalDNS.replicaCount }}
  selector:
    matchLabels:
      {{- include "operator.labels" . | nindent 6 }}
      app.kubernetes.io/name: externalDNS
      app.kubernetes.io/instance: {{ include "operator.fullname" . }}-external-dns
  template:
    metadata:
      labels:
        {{- include "operator.labels" . | nindent 8 }}
        app.kubernetes.io/name: externalDNS
        app.kubernetes.io/instance: {{ include "operator.fullname" . }}-external-dns
    spec:
      serviceAccountName: {{ include "operator.fullname" . }}-external-dns
      {{- with .Values.externalDNS.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: external-dns
          {{- with .Values.externalDNS.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "operator.externalDNS.image" . }}
          imagePullPolicy: {{ .Values.externalDNS.image.pullPolicy }}
          args:
            - --log-level={{ .Values.externalDNS.log.level }}
            - --log-format={{ .Values.externalDNS.log.format }}
            - --interval={{ .Values.externalDNS.interval }}
            {{- range .Values.externalDNS.sources }}
            - --source={{ . }}
            {{- end }}
            - --policy={{ .Values.externalDNS.policy }}
            - --registry={{ .Values.externalDNS.registry }}
            - --namespace={{ .Release.Namespace }}
            - --txt-owner-id=sequencer
            {{- range .Values.externalDNS.recordTypes }}
            - --managed-record-types={{ . }}
            {{- end }}
            - --provider={{ $providerName }}
          {{- with .Values.externalDNS.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            {{- toYaml .Values.externalDNS.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.externalDNS.readinessProbe | nindent 12 }}
          volumeMounts:
          {{- with .Values.externalDNS.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.externalDNS.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.externalDNS.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.externalDNS.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
