apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.fullname" . }}-external-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}