//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package providers

import (
	"se.quencer.io/api/v1alpha1/utils"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSSpec) DeepCopyInto(out *AWSSpec) {
	*out = *in
	if in.Route53 != nil {
		in, out := &in.Route53, &out.Route53
		*out = new(Route53Spec)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(utils.SecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSSpec.
func (in *AWSSpec) DeepCopy() *AWSSpec {
	if in == nil {
		return nil
	}
	out := new(AWSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSSpec) DeepCopyInto(out *CloudflareDNSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSSpec.
func (in *CloudflareDNSSpec) DeepCopy() *CloudflareDNSSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRouteSpec) DeepCopyInto(out *CloudflareRouteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRouteSpec.
func (in *CloudflareRouteSpec) DeepCopy() *CloudflareRouteSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareSpec) DeepCopyInto(out *CloudflareSpec) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
	if in.Tunnel != nil {
		in, out := &in.Tunnel, &out.Tunnel
		*out = new(CloudflareTunnelSpec)
		**out = **in
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(CloudflareDNSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareSpec.
func (in *CloudflareSpec) DeepCopy() *CloudflareSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelSpec) DeepCopyInto(out *CloudflareTunnelSpec) {
	*out = *in
	out.Route = in.Route
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelSpec.
func (in *CloudflareTunnelSpec) DeepCopy() *CloudflareTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelSpec)
	in.DeepCopyInto(out)
	return out
}
