apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver
  namespace: sequencer-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: solver
    app.kubernetes.io/instance: solver
    app.kubernetes.io/component: cert-manager
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: solver
      app.kubernetes.io/name: solver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: solver
        app.kubernetes.io/name: solver
    spec:
      containers:
      - command:
        args:
          - --tls-cert-file=/tls/tls.crt
          - --tls-private-key-file=/tls/tls.key
        image: solver:dev
        name: solver
        env:
          - name: GROUP_NAME
            value: solver.se.quencer.io
          - name: SOLVER_NAME
            value: external-dns
          - name: SEQUENCER_NAMESPACE
            value: sequencer-system
        envFrom:
          - configMapRef:
              name: controller-manager
        ports:
          - containerPort: 443
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: certs
            mountPath: /tls
            readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: webhook-server-cert
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10