# This RoleBinding exists so the solver can retrieve
# The authentication information to be able to connect and
# authenticate to K8s API Server.
# The big difference here is that this needs to be created as a scoped
# resource within the `kube-system` namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: solverrolebinding
    app.kubernetes.io/instance: solver-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
    app.kubernetes.io/managed-by: kustomize
  name: solver-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: sequencer-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:dns01-solver
  labels:
    app: sequencer-solver
rules:
  - apiGroups:
      - solver.se.quencer.io
    resources:
      - '*'
    verbs:
      - 'create'