apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dns-sequencer
    {{- include "operator.labels" . | nindent 4 }}
  name: {{ template "operator.fullname" . }}:dns-manager-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
- apiGroups:
  - se.quencer.io
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
