apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}-dns-controller
  namespace: sequencer-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: dns-controller
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: dns-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: dns-controller
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command: ["/dns"]
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: {{ quote .Values.dnsController.image }}
        name: manager
        env:
          - name: DNS_SEQUENCER_PROVIDER_NAME
            value: {{ .Values.dnsController.providerName }}  
          {{- toYaml .Values.dnsController.env | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: {{ include "operator.fullname" . }}-dns-controller
      terminationGracePeriodSeconds: 10
