apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dns-sequencer
    {{- include "operator.labels" . | nindent 4 }}
  name: {{ template "operator.labels" . }}:dns-leader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "operator.labels" . }}:dns-leader
subjects:
- kind: ServiceAccount
  name: {{ include "operator.fullname" . }}-dns-controller
  namespace: {{ .Release.Namespace }}

