apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  name: {{ include "operator.fullname" . }}-dns-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.dnsController.serviceAccount.annotations | nindent 4 }}