# permissions for end users to view builds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: build-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
    app.kubernetes.io/managed-by: kustomize
  name: build-viewer-role
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - builds/status
  verbs:
  - get
