# permissions for end users to edit components.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: component-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sequencer
    app.kubernetes.io/part-of: sequencer
    app.kubernetes.io/managed-by: kustomize
  name: component-editor-role
rules:
- apiGroups:
  - se.quencer.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - components/status
  verbs:
  - get
