---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - builds/finalizers
  verbs:
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - builds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces/conditions
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - se.quencer.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
